/**
 * ============================================
 * MARKDOWN SERVICE
 * Converts ProjectBriefOutput to Markdown
 * ============================================
 */

import { ProjectBriefOutput } from "../ai/types";

/**
 * Build Markdown for Research Document
 */
function buildResearchMarkdown(brief: ProjectBriefOutput): string {
    const lines: string[] = [];

    lines.push(`# Research Proposal Document`);
    lines.push(`## ${brief.title}`);
    lines.push(``);
    lines.push(`> Generated by Planify | ${new Date().toLocaleDateString()} | Version 1.0 (${brief.methodology ? 'Final' : 'Draft'})`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);

    // Abstract
    lines.push(`## 1. Abstract`);
    lines.push(``);
    lines.push(brief.abstract || brief.overview || 'Abstract not provided');
    lines.push(``);

    // Research Questions
    lines.push(`## 2. Research Questions`);
    lines.push(``);
    if (brief.researchQuestions?.length) {
        brief.researchQuestions.forEach((q: any, i: number) => {
            const text = typeof q === 'string' ? q : (q.question || JSON.stringify(q));
            lines.push(`${i + 1}. ${text}`);
        });
    } else {
        lines.push(`- Research questions not yet defined`);
    }
    lines.push(``);

    // Objectives
    lines.push(`## 3. Research Objectives`);
    lines.push(``);
    if (brief.objectives?.length) {
        brief.objectives.forEach((o: any) => {
            const text = typeof o === 'string' ? o : (o.objective || o.id || JSON.stringify(o));
            lines.push(`- ${text}`);
        });
    } else {
        lines.push(`- Objectives not specified`);
    }
    lines.push(``);

    // Methodology
    lines.push(`## 4. Research Methodology`);
    lines.push(``);
    if (brief.methodology) {
        lines.push(`### 4.1 Approach`);
        lines.push(brief.methodology.approach || 'Not specified');
        lines.push(``);

        if (brief.methodology.population) {
            lines.push(`### 4.2 Population & Sample`);
            lines.push(brief.methodology.population);
            lines.push(``);
        }

        if (brief.methodology.dataCollection) {
            lines.push(`### 4.3 Data Collection`);
            const methods = Array.isArray(brief.methodology.dataCollection.methods) ? brief.methodology.dataCollection.methods.join(', ') : (brief.methodology.dataCollection.methods || 'N/A');
            const instruments = Array.isArray(brief.methodology.dataCollection.instruments) ? brief.methodology.dataCollection.instruments.join(', ') : (brief.methodology.dataCollection.instruments || 'N/A');
            lines.push(`- **Methods:** ${methods}`);
            lines.push(`- **Instruments:** ${instruments}`);
            lines.push(``);
        }

        if (brief.methodology.dataAnalysis) {
            lines.push(`### 4.4 Data Analysis`);
            const techniques = Array.isArray(brief.methodology.dataAnalysis.techniques) ? brief.methodology.dataAnalysis.techniques.join(', ') : (brief.methodology.dataAnalysis.techniques || 'N/A');
            const tools = Array.isArray(brief.methodology.dataAnalysis.software) ? brief.methodology.dataAnalysis.software.join(', ') :
                (brief.methodology.dataAnalysis.software ||
                    (Array.isArray(brief.methodology.dataAnalysis.tools) ? brief.methodology.dataAnalysis.tools.join(', ') : (brief.methodology.dataAnalysis.tools || 'N/A')));
            lines.push(`- **Techniques:** ${techniques}`);
            lines.push(`- **Tools/Software:** ${tools}`);
            lines.push(``);
        }
    } else {
        lines.push(`Methodology details available in Polished Mode`);
        lines.push(``);
    }

    // Expected Outcomes
    lines.push(`## 5. Expected Outcomes`);
    lines.push(``);
    if (brief.expectedOutcomes?.length) {
        brief.expectedOutcomes.forEach((o: any) => {
            const text = typeof o === 'string' ? o : (o.outcome || JSON.stringify(o));
            lines.push(`- ${text}`);
        });
    } else {
        lines.push(`- Expected outcomes defined in Polished Mode`);
    }
    lines.push(``);

    // Timeline
    lines.push(`## 6. Research Timeline`);
    lines.push(``);
    if (brief.timeline?.phases) {
        brief.timeline.phases.forEach((p: any) => {
            lines.push(`- **${p.name || p.phase || 'Phase'}**: ${p.duration || p.weeks || 'TBD'}`);
        });
    } else {
        lines.push(`Timeline details available in Polished Mode`);
    }
    lines.push(``);

    // Variables
    if (brief.variables?.length) {
        lines.push(`## 7. Research Variables`);
        lines.push(``);
        lines.push(`| Variable | Type | Indicators |`);
        lines.push(`|----------|------|------------|`);
        brief.variables.forEach((v: any) => {
            const indicators = Array.isArray(v.indicators) ? v.indicators.join(', ') : (v.indicators || 'N/A');
            lines.push(`| ${v.name || v.variable || 'Variable'} | ${v.type || 'N/A'} | ${indicators} |`);
        });
        lines.push(``);
    }

    // Hypotheses
    if (brief.hypotheses?.length) {
        lines.push(`## ${brief.variables ? '8' : '7'}. Hypotheses`);
        lines.push(``);
        brief.hypotheses.forEach((h: any, i: number) => {
            const text = typeof h === 'string' ? h : (h.hypothesis || h.statement || JSON.stringify(h));
            lines.push(`${i + 1}. ${text}`);
        });
        lines.push(``);
    }

    // Diagram
    if (brief.diagram) {
        lines.push(`## Appendix: Conceptual Framework`);
        lines.push(``);
        lines.push(brief.diagram.description || 'Research conceptual framework');
        lines.push(``);
        lines.push('```mermaid');
        lines.push(brief.diagram.diagram);
        lines.push('```');
        lines.push(``);
    }

    return lines.join('\n');
}

/**
 * Build Markdown for Web/Mobile Application (PRD)
 */
function buildAppMarkdown(brief: ProjectBriefOutput): string {
    const lines: string[] = [];

    lines.push(`# Product Requirements Document (PRD)`);
    lines.push(`## ${brief.title}`);
    lines.push(``);
    lines.push(`> Generated by Planify | ${new Date().toLocaleDateString()} | Version 1.0 (${brief.srsModules ? 'Polished' : 'Draft'}) | Platform: ${brief.platformCategory || 'Web Application'}`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);

    // 1. Executive Summary
    lines.push(`## 1. Executive Summary & Project Brief`);
    lines.push(``);
    lines.push(`### 1.1 Project Description`);
    lines.push(brief.overview);
    lines.push(``);

    lines.push(`### 1.2 Target Audience (User Personas)`);
    lines.push(`- **Primary:** ${brief.targetAudience?.primary || brief.targetAudience}`);
    if (brief.targetAudience?.secondary) lines.push(`- **Secondary:** ${brief.targetAudience.secondary}`);
    if (brief.targetAudience?.admin) lines.push(`- **Admin:** ${brief.targetAudience.admin}`);
    lines.push(``);

    lines.push(`### 1.3 Project Objectives`);
    brief.objectives?.forEach((o: any) => {
        lines.push(`- ${typeof o === 'string' ? o : JSON.stringify(o)}`);
    });
    lines.push(``);

    // 2. Problem Statement
    lines.push(`## 2. Problem Statement & Business Value`);
    lines.push(``);
    lines.push(`### 2.1 Key Pain Points`);
    if (brief.problemStatement?.painPoints?.length) {
        brief.problemStatement.painPoints.forEach((p: string) => lines.push(`- ${p}`));
    } else {
        lines.push(`- Data not available in Draft mode`);
    }
    lines.push(``);

    lines.push(`### 2.2 Business Impact (Cost of Inaction)`);
    lines.push(brief.problemStatement?.businessImpact || 'Data not available in Draft mode');
    lines.push(``);

    // 3. Success Criteria
    lines.push(`## 3. Goals & Success Criteria`);
    lines.push(``);
    lines.push(`### 3.1 Key Performance Indicators (KPIs)`);
    lines.push(``);
    lines.push(`| Metric | Target |`);
    lines.push(`|--------|--------|`);
    if (brief.successCriteria?.length) {
        brief.successCriteria.forEach((s: any) => {
            if (typeof s === 'string') {
                lines.push(`| Success Criteria | ${s} |`);
            } else {
                lines.push(`| ${s.metric} | ${s.target} |`);
            }
        });
    }
    lines.push(``);

    // 4. Feature List
    lines.push(`## 4. Feature List & Prioritization (MoSCoW)`);
    lines.push(``);
    lines.push(`| No | Feature | Description | Priority |`);
    lines.push(`|----|---------|-------------|----------|`);
    brief.keyFeatures?.forEach((f: any, i: number) => {
        lines.push(`| ${i + 1} | **${f.name}** | ${f.description} | ${f.priority || 'Should'} |`);
    });
    lines.push(``);

    // 5. User Flow
    lines.push(`## 5. User Flow (Main Scenario)`);
    lines.push(``);
    if (brief.userFlow?.steps?.length) {
        brief.userFlow.steps.forEach((s: string, i: number) => {
            lines.push(`${i + 1}. ${s}`);
        });
    } else {
        lines.push(`- Flow not defined in Draft mode`);
    }
    lines.push(``);

    if (brief.userFlow?.diagramDsl) {
        lines.push(`### 5.2 Flow Diagram`);
        lines.push(``);
        lines.push('```mermaid');
        lines.push(brief.userFlow.diagramDsl);
        lines.push('```');
        lines.push(``);
    }

    // 6. SRS Modules
    lines.push(`## 6. Software Requirements Specification (SRS)`);
    lines.push(``);
    if (brief.srsModules?.length) {
        brief.srsModules.forEach((mod: any) => {
            lines.push(`### Module: ${mod.moduleName}`);
            lines.push(``);
            mod.requirements?.forEach((req: any) => {
                lines.push(`#### ${req.id || 'REQ'} - ${req.userStory?.split(',')[0] || 'User Story'}`);
                lines.push(``);
                lines.push(`> *"${req.userStory}"*`);
                lines.push(``);
                if (req.acceptanceCriteria?.length) {
                    lines.push(`**Acceptance Criteria:**`);
                    req.acceptanceCriteria.forEach((ac: string) => lines.push(`- ${ac}`));
                    lines.push(``);
                }
            });
        });
    } else if (brief.keyFeatures?.some((f: any) => f.userStory)) {
        brief.keyFeatures.forEach((f: any, i: number) => {
            lines.push(`### Feature ${i + 1}: ${f.name}`);
            if (f.userStory) lines.push(`> *"${f.userStory}"*`);
            if (f.acceptanceCriteria?.length) {
                lines.push(`**Acceptance Criteria:**`);
                f.acceptanceCriteria.forEach((ac: string) => lines.push(`- ${ac}`));
            }
            lines.push(``);
        });
    } else {
        lines.push(`SRS Details available in Polished Mode only.`);
        lines.push(``);
    }

    // 7. Tech Stack
    lines.push(`## 7. Technical Architecture & Non-Functional Requirements`);
    lines.push(``);
    lines.push(`### 7.1 Tech Stack Strategy`);
    lines.push(``);
    lines.push(`| Category | Technology | Selection Reason |`);
    lines.push(`|----------|------------|------------------|`);
    brief.recommendedTechStack?.forEach((t: any) => {
        lines.push(`| ${t.category} | **${t.technology}** | ${t.reason} |`);
    });
    lines.push(``);

    lines.push(`### 7.2 Non-Functional Requirements`);
    if (brief.nonFunctionalRequirements) {
        lines.push(`- **Security:** ${brief.nonFunctionalRequirements.security?.join(', ') || 'Standard HTTPS/Auth'}`);
        lines.push(`- **Performance:** ${brief.nonFunctionalRequirements.performance?.join(', ') || 'Optimization required'}`);
        lines.push(`- **Scalability:** ${brief.nonFunctionalRequirements.scalability?.join(', ') || 'Vertical scaling'}`);
    } else {
        lines.push(`NFRs defined in Polished Mode.`);
    }
    lines.push(``);

    // 8. Scope
    lines.push(`## 8. Scope & MVP Definition`);
    lines.push(``);
    lines.push(`### 8.1 In-Scope`);
    if (brief.scope?.inScope?.length) {
        brief.scope.inScope.forEach((s: string) => lines.push(`- ${s}`));
    } else {
        lines.push(`- Defined in Polished Mode`);
    }
    lines.push(``);
    lines.push(`### 8.2 Out-of-Scope`);
    if (brief.scope?.outOfScope?.length) {
        brief.scope.outOfScope.forEach((s: string) => lines.push(`- ${s}`));
    } else {
        lines.push(`- Defined in Polished Mode`);
    }
    lines.push(``);

    // 9. Risks
    lines.push(`## 9. Risk, Assumptions & Mitigation`);
    lines.push(``);
    lines.push(`| Risk | Type | Mitigation |`);
    lines.push(`|------|------|------------|`);
    if (brief.risks?.length) {
        brief.risks.forEach((r: any) => {
            lines.push(`| ${r.risk} | ${r.type} | ${r.mitigation} |`);
        });
    } else {
        lines.push(`| Risks analyzed in Polished Mode | - | - |`);
    }
    lines.push(``);

    // 10. Clarification Log
    lines.push(`## 10. AI Clarification Log`);
    lines.push(``);
    lines.push(`*This log tracks technical decisions assisted by AI consultation.*`);
    lines.push(``);
    lines.push(`| Date | Question / Topic | AI Clarification / Advice |`);
    lines.push(`|------|------------------|---------------------------|`);
    if (brief.clarificationLog?.length) {
        brief.clarificationLog.forEach((l: any) => {
            lines.push(`| ${l.date} | ${l.topic} | ${l.advice} |`);
        });
    } else {
        lines.push(`| - | Available in Polished Mode only | - |`);
    }
    lines.push(``);

    // Diagram
    if (brief.diagram) {
        lines.push(`## Appendix: System Architecture Diagram`);
        lines.push(``);
        lines.push(brief.diagram.description || '');
        lines.push(``);
        lines.push('```mermaid');
        lines.push(brief.diagram.diagram);
        lines.push('```');
        lines.push(``);
    }

    return lines.join('\n');
}

export const markdownService = {
    /**
     * Generate Markdown string from ProjectBriefOutput
     * Auto-detects document type (research vs app PRD)
     */
    generateMarkdown(brief: ProjectBriefOutput): string {
        const isResearch = brief.platformCategory?.toLowerCase().includes('research');
        return isResearch ? buildResearchMarkdown(brief) : buildAppMarkdown(brief);
    },
};
