/**
 * ============================================
 * PDF CONTROLLER
 * Handles PDF generation requests
 * ============================================
 */

import { Request, Response } from "express";
import { asyncHandler } from "../utils/async-handler";
import { pdfService } from "../services/pdf/pdf.service";
import { ProjectBriefOutput } from "../services/ai/types";
import { coinService, COIN_COSTS } from "../services/coin";
import { ErrorCodes } from "../utils/app-error";

export const pdfController = {
    /**
     * Generate PDF from Project Brief
     * @route POST /api/pdf/brief
     * @body ProjectBriefOutput
     */
    generateBriefPdf: asyncHandler(
        async (req: Request, res: Response): Promise<any> => {
            const brief: ProjectBriefOutput = req.body;
            const userId = (req as any).user?.userId || "anonymous";

            if (!brief || !brief.title) {
                return res.status(400).json({
                    success: false,
                    message: "Invalid project brief data",
                    code: ErrorCodes.VALIDATION_ERROR,
                });
            }

            // Check coins
            const cost = COIN_COSTS.PDF;
            const hasEnough = await coinService.hasEnough(userId, cost);

            if (!hasEnough) {
                const balance = await coinService.getBalance(userId);
                return res.status(402).json({
                    success: false,
                    message: `Insufficient coins. Need ${cost}, have ${balance}`,
                    code: "INSUFFICIENT_COINS",
                });
            }

            // Convert brief to HTML (Full 10-Section PRD)
            const htmlContent = `
                <!-- Cover Page -->
                <div class="cover-page">
                    <div class="cover-title">Product Requirements Document (PRD)</div>
                    <div class="cover-subtitle">Project: ${brief.title}</div>
                    
                    <div class="cover-info">
                        <div class="cover-info-item">
                            <span class="cover-label">Project Name:</span> ${brief.title}
                        </div>
                        <div class="cover-info-item">
                            <span class="cover-label">Version:</span> 1.0 (DRAFT)
                        </div>
                        <div class="cover-info-item">
                            <span class="cover-label">Date:</span> ${new Date().toLocaleDateString()}
                        </div>
                        <div class="cover-info-item">
                            <span class="cover-label">Status:</span> ${brief.srsModules ? 'Polished / Final' : 'Draft / Review'}
                        </div>
                         <div class="cover-info-item">
                            <span class="cover-label">Platform:</span> ${brief.platformCategory || 'Web Application'}
                        </div>
                    </div>
                </div>

                <!-- Watermark / Header -->
                <div style="position: fixed; top: 10px; right: 20px; color: #aaa; font-size: 10px; font-weight: bold; z-index: 9999;">
                    Generated by Planify
                </div>

                <!-- 1. Executive Summary -->
                <div class="section">
                    <h3>1. Executive Summary & Project Brief</h3>
                    
                    <h4>1.1 Project Description</h4>
                    <p>${brief.overview}</p>

                    <h4>1.2 Target Audience (User Personas)</h4>
                    <ul>
                         <li><strong>Primary:</strong> ${brief.targetAudience?.primary || brief.targetAudience}</li>
                         ${brief.targetAudience?.secondary ? `<li><strong>Secondary:</strong> ${brief.targetAudience.secondary}</li>` : ''}
                         ${brief.targetAudience?.admin ? `<li><strong>Admin:</strong> ${brief.targetAudience.admin}</li>` : ''}
                    </ul>
                    
                    <h4>1.3 Project Objectives</h4>
                    <ul>
                        ${brief.objectives.map(o => `<li>${o}</li>`).join("")}
                    </ul>
                </div>

                <!-- 2. Problem Statement -->
                <div class="section page-break-before">
                    <h3>2. Problem Statement & Business Value</h3>
                    
                    <h4>2.1 Key Pain Points</h4>
                    <ul>
                        ${brief.problemStatement?.painPoints?.map((p: string) => `<li>${p}</li>`).join("") || "<li>Data not available in Draft mode</li>"}
                    </ul>

                    <h4>2.2 Business Impact (Cost of Inaction)</h4>
                    <p>${brief.problemStatement?.businessImpact || "Data not available in Draft mode"}</p>
                </div>

                <!-- 3. Goals & Success Criteria -->
                <div class="section">
                    <h3>3. Goals & Success Criteria</h3>
                    
                    <h4>3.1 Key Performance Indicators (KPIs)</h4>
                     <table>
                        <thead>
                            <tr>
                                <th style="width: 40%">Metric</th>
                                <th style="width: 60%">Target</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${brief.successCriteria?.map((s: any) => typeof s === 'string' ? `<tr><td>Success Criteria</td><td>${s}</td></tr>` : `
                                <tr>
                                    <td>${s.metric}</td>
                                    <td>${s.target}</td>
                                </tr>
                            `).join("")}
                        </tbody>
                    </table>
                </div>

                <!-- 4. Feature List (MoSCoW) -->
                <div class="section page-break-before">
                    <h3>4. Feature List & Prioritization (MoSCoW)</h3>
                    <table>
                        <thead>
                            <tr>
                                <th style="width: 5%">No</th>
                                <th style="width: 25%">Feature</th>
                                <th style="width: 50%">Description</th>
                                <th style="width: 20%">Priority</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${brief.keyFeatures.map((f, i) => `
                                <tr>
                                    <td>${i + 1}</td>
                                    <td><strong>${f.name}</strong></td>
                                    <td>${f.description}</td>
                                    <td><span class="tag">${f.priority || 'Should'}</span></td>
                                </tr>
                            `).join("")}
                        </tbody>
                    </table>
                </div>

                 <!-- 5. User Flow -->
                <div class="section page-break-before">
                    <h3>5. User Flow (Main Scenario)</h3>
                    <ol>
                         ${brief.userFlow?.steps?.map((s: string) => `<li>${s}</li>`).join("") || "<li>Flow not defined in Draft mode</li>"}
                    </ol>
                     ${brief.userFlow?.diagramDsl ? `
                    <div class="mermaid-section">
                        <h4>5.2 Flow Diagram</h4>
                        <div class="mermaid">
                            ${brief.userFlow.diagramDsl}
                        </div>
                    </div>
                    ` : ''}
                </div>

                <!-- 6. SRS Modules -->
                <div class="section page-break-before">
                    <h3>6. Software Requirements Specification (SRS)</h3>
                    ${brief.srsModules?.map((mod: any) => `
                        <h4>Module: ${mod.moduleName}</h4>
                        ${mod.requirements.map((req: any) => `
                             <div class="module-box">
                                <div class="module-title">${req.id || 'REQ'} - ${req.userStory.split(',')[0] || 'User Story'}</div>
                                <div class="user-story">
                                    "${req.userStory}"
                                </div>
                                <div style="font-size: 0.9em; margin-top: 10px;">
                                    <strong>Acceptance Criteria:</strong>
                                    <ul style="margin: 5px 0 0 20px;">
                                        ${req.acceptanceCriteria.map((ac: string) => `<li>${ac}</li>`).join('')}
                                    </ul>
                                </div>
                            </div>
                        `).join('')}
                    `).join("") || "<p>SRS Details available in Polished Mode only.</p>"}

                    <!-- Fallback for Draft mode functionality if SRS missing but KeyFeatures present -->
                     ${!brief.srsModules && brief.keyFeatures.some(f => f.userStory) ?
                    brief.keyFeatures.map((f, i) => `
                            <div class="module-box">
                                <div class="module-title">Feature ${i + 1}: ${f.name}</div>
                                <div class="user-story">"${f.userStory || ''}"</div>
                                ${f.acceptanceCriteria ? `<ul>${f.acceptanceCriteria.map(ac => `<li>${ac}</li>`).join('')}</ul>` : ''}
                            </div>
                        `).join("") : ''
                }
                </div>

                <!-- 7. Technical Architecture -->
                <div class="section page-break-before">
                    <h3>7. Technical Architecture & Non-Functional Req</h3>
                    
                    <h4>7.1 Tech Stack Strategy</h4>
                    <table>
                        <thead>
                            <tr>
                                <th style="width: 20%">Category</th>
                                <th style="width: 30%">Technology</th>
                                <th style="width: 50%">Selection Reason</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${brief.recommendedTechStack.map(t => `
                                <tr>
                                    <td>${t.category}</td>
                                    <td><strong>${t.technology}</strong></td>
                                    <td>${t.reason}</td>
                                </tr>
                            `).join("")}
                        </tbody>
                    </table>

                    <h4>7.2 Non-Functional Requirements</h4>
                     ${brief.nonFunctionalRequirements ? `
                        <ul>
                            <li><strong>Security:</strong> ${brief.nonFunctionalRequirements.security?.join(', ') || 'Standard HTTPS/Auth'}</li>
                            <li><strong>Performance:</strong> ${brief.nonFunctionalRequirements.performance?.join(', ') || 'Optimization required'}</li>
                             <li><strong>Scalability:</strong> ${brief.nonFunctionalRequirements.scalability?.join(', ') || 'Vertical scaling'}</li>
                        </ul>
                     ` : "<p>NFRs defined in Polished Mode.</p>"}
                </div>
                
                 <!-- 8. Scope & MVP -->
                <div class="section">
                    <h3>8. Scope & MVP Definition</h3>
                    <div style="display: flex; justify-content: space-between;">
                        <div style="width: 48%;">
                            <h4>8.1 In-Scope</h4>
                            <ul>${brief.scope?.inScope?.map((s: string) => `<li>${s}</li>`).join('') || '<li>Defined in Polished Mode</li>'}</ul>
                        </div>
                        <div style="width: 48%;">
                             <h4>8.2 Out-of-Scope</h4>
                            <ul>${brief.scope?.outOfScope?.map((s: string) => `<li>${s}</li>`).join('') || '<li>Defined in Polished Mode</li>'}</ul>
                        </div>
                    </div>
                </div>

                 <!-- 9. Risks -->
                <div class="section">
                    <h3>9. Risk, Assumptions & Mitigation</h3>
                    <table>
                        <thead>
                            <tr>
                                <th>Risk</th>
                                <th>Type</th>
                                <th>Mitigation</th>
                            </tr>
                        </thead>
                         <tbody>
                            ${brief.risks?.map((r: any) => `
                                <tr>
                                    <td>${r.risk}</td>
                                    <td>${r.type}</td>
                                    <td>${r.mitigation}</td>
                                </tr>
                            `).join("") || "<tr><td colspan='3'>Risks analyzed in Polished Mode</td></tr>"}
                        </tbody>
                    </table>
                </div>

                <!-- 10. AI Clarification Log -->
                <div class="section">
                    <h3>10. AI Clarification Log (Optional)</h3>
                    <p style="font-size: 0.9em; color: #666; margin-bottom: 10px;">This log tracks technical decisions assisted by AI consultation.</p>
                     <table>
                        <thead>
                            <tr>
                                <th style="width: 15%">Date</th>
                                <th style="width: 35%">Question / Topic</th>
                                <th style="width: 50%">AI Clarification / Advice</th>
                            </tr>
                        </thead>
                         <tbody>
                            ${brief.clarificationLog?.map((l: any) => `
                                <tr>
                                    <td>${l.date}</td>
                                    <td>${l.topic}</td>
                                    <td>${l.advice}</td>
                                </tr>
                            `).join("") || "<tr><td colspan='3'>Available in Polished Mode only.</td></tr>"}
                        </tbody>
                    </table>
                </div>
                
                ${brief.diagram ? `
                <div class="mermaid-section">
                    <h3>Appendix: System Architecture Diagram</h3>
                    <p style="margin-bottom: 1rem;">${brief.diagram.description}</p>
                    <div class="mermaid">
                        ${brief.diagram.diagram}
                    </div>
                </div>
                ` : ''}
            `;

            const fullHtml = pdfService.createHtmlTemplate(brief.title, htmlContent);

            // Generate PDF
            const pdfBuffer = await pdfService.generatePdf(fullHtml);

            // Deduct coins
            await coinService.deduct(userId, cost);

            // Send response
            res.setHeader("Content-Type", "application/pdf");
            res.setHeader("Content-Disposition", `attachment; filename="${brief.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_brief.pdf"`);
            // Custom header to inform client about updated coins (difficult in binary response, so we skip or use header)
            const newBalance = await coinService.getBalance(userId);
            res.setHeader("X-Coins-Remaining", newBalance.toString());

            return res.send(pdfBuffer);
        }
    ),
};
