import { z } from "zod";

export const exportPdfSchema = z.object({
  body: z.object({
    title: z.string().min(1, "Title is required").max(200),
    overview: z.string().optional(),
    platformCategory: z.string().optional(),
    targetAudience: z.any().optional(),
    objectives: z.array(z.any()).optional(),
    problemStatement: z.any().optional(),
    successCriteria: z.array(z.any()).optional(),
    keyFeatures: z.array(z.any()).optional(),
    userFlow: z.any().optional(),
    srsModules: z.array(z.any()).optional(),
    recommendedTechStack: z.array(z.any()).optional(),
    nonFunctionalRequirements: z.any().optional(),
    scope: z.any().optional(),
    risks: z.array(z.any()).optional(),
    clarificationLog: z.array(z.any()).optional(),
    diagram: z.any().optional(),
    abstract: z.string().optional(),
    researchQuestions: z.array(z.any()).optional(),
    methodology: z.any().optional(),
    expectedOutcomes: z.array(z.any()).optional(),
    timeline: z.any().optional(),
    variables: z.array(z.any()).optional(),
    hypotheses: z.array(z.any()).optional(),
  }),
});

export const exportMarkdownSchema = z.object({
  body: z.object({
    title: z.string().min(1, "Title is required").max(200),
    overview: z.string().optional(),
    platformCategory: z.string().optional(),
    targetAudience: z.any().optional(),
    objectives: z.array(z.any()).optional(),
    problemStatement: z.any().optional(),
    successCriteria: z.array(z.any()).optional(),
    keyFeatures: z.array(z.any()).optional(),
    userFlow: z.any().optional(),
    srsModules: z.array(z.any()).optional(),
    recommendedTechStack: z.array(z.any()).optional(),
    nonFunctionalRequirements: z.any().optional(),
    scope: z.any().optional(),
    risks: z.array(z.any()).optional(),
    clarificationLog: z.array(z.any()).optional(),
    diagram: z.any().optional(),
    abstract: z.string().optional(),
    researchQuestions: z.array(z.any()).optional(),
    methodology: z.any().optional(),
    expectedOutcomes: z.array(z.any()).optional(),
    timeline: z.any().optional(),
    variables: z.array(z.any()).optional(),
    hypotheses: z.array(z.any()).optional(),
  }),
});